keycloak/keycloak-oauth-sig

fapi-conformance-suite-configs/fapi-rw-id2-with-mtls-ES256-ES256.json
fapi-conformance-suite-configs/fapi-rw-id2-with-mtls-PS256-PS256.json
fapi-conformance-suite-configs/fapi-rw-id2-with-mtls-RS256-PS256.json
fapi-conformance-suite-configs/fapi-rw-id2-with-private-key-ES256-ES256.json
fapi-conformance-suite-configs/fapi-rw-id2-with-private-key-PS256-PS256.json
fapi-conformance-suite-configs/fapi-rw-id2-with-private-key-RS256-PS256.json
fapi-conformance-suite-configs/generate-fapi-conformance-suite-configs.sh

See the following ticket and commit:
- https://gitlab.com/openid/conformance-suite/-/issues/767
- https://gitlab.com/openid/conformance-suite/-/commit/9857652fad3e8d99c61dada46d877a17b29309a2

Fix #99 Add email scope since the latest conformance test requires multiple scopes in the new test `fapi-rw-id2-ensure-other-scope-order-succeeds`

---

FAPI-SIG/meetings/11th/11th_MTG_Minute.txt

add 11th meeting minute

---

.env
docker-compose.yml
keycloak/realm.json
test-runner/test-runner-entrypoint.sh

For https://github.com/keycloak/kc-sig-fapi/issues/161

For fapi 1 0 final

---

.env

https://github.com/keycloak/kc-sig-fapi/issues/169

conformance suite vup to 4.1.11

---

members.adoc

I recently joined the ANS, in the same team as Charlène Sophie, we both will be working on OIDC and especially CIBA

Update members (adding Arnaud Bourhis from ANS)

---

README.md
auth_entity_server/main.go
https/generate-server.sh

…e testsuite from https://www.certification.openid.net

FAPI CIBA Ping mode tweaks for run against 

---

.env

New tests:
!1025 BrazilDCR: Additional test that uses software statement with invalid signature
!1027 BrazilDCR: Additional test that invalid redirect url
!1027 BrazilDCR: The test is now failed if the software statement does not contain the required redirect url
!1026 !1027 Brazil: Add support for using payments API instead of accounts API; see example configuration: https://gitlab.com/openid/conformance-suite/-/wikis/Brazil-Example-Configuration#private_key_jwt-with-payments-api
Bug fixes:
#911 FAPI: Additional invalid_grant error in 'wrong client id at token endpoint'
#808 'Proceed with test' button sometimes requires two clicks
!1028 FAPI RP: Fix aud validation for client assertions at PAR endpoint
!1028 Brazil RP: Return valid permissions group from consents endpoint, fix missing …

Update conformance suite to v4.1.20

---

README.md

@tnorimat FYI. I've did this small update in README.md

Add aes.keycloak-fapi.org into README.md

---

.env

Released: 2021-08-04
Bug fixes:
!1030 BrazilDCR: Fix tls_client_auth_subject_dn in the dynamic registration request being encoded incorrectly if it contains non-ascii characters
#927 Brazil: Request more permissions to cater for banks that don't support ACCOUNTS_READ
Source: https://gitlab.com/openid/conformance-suite/-/tags/release-v4.1.21
FYI : @tnorimat @mposolda @pedroigor

Update conformance suite to v4.1.21

---

.env

https://gitlab.com/openid/conformance-suite/-/tags
@tnorimat  @mposolda @pedroigor

Update conformance suite and keycloak

---

docker-compose-keycloak.yml

Keycloak 10820 Fixes to hostname affects conformance test automatic run environment

---

README.md

Add Passed Conformance Tests per Keycloak version section to README.md

---

.env
README.md
keycloak/realm-cdr.json
keycloak/realm.json

Update Keycloak images to 18.0.0

---

README.md

OpenID Connect OP for Logout Profiles conformance test automated run environment

---

README.md

Update FAPI-SIG's scope

---

.env

Update conformance suite to v4.1.25

Update conformance suite to v4.1.25

---

.env
README.md

Update Keycloak images to 19.0.2

---

.env
README.md
docker-compose-keycloak-legacy.yml
docker-compose-keycloak.yml
keycloak/Dockerfile.legacy
keycloak/keycloak-custom.properties
keycloak/realm.json

Update Keycloak images to 20.0.0

---

FAPI-SIG/meetings/40th/40th_MTG_Minute.txt

Add FAPI-SIG 40th meeting minute

---

.env
README.md

Update Keycloak images to 20.0.2

---

FAPI-SIG/meetings/41st/41st_MTG_Minute.txt

Add 41st meeting minute

---

.env
README.md

Update Keycloak images to 20.0.3

---

FAPI-SIG/meetings/42nd/42nd_MTG_Minute.txt

Add FAPI-SIG 42nd meeting minute

---

.env
README.md

Update Keycloak images to 20.0.5

---

.env
README.md

Update Keycloak images to 21.0.0

---

FAPI-SIG/meetings/43rd/43rd_MTG_Minute.txt

Add FAPI-SIG 43rd meeting minute

---

.env
README.md

Update Keycloak images to 21.0.2

---

FAPI-SIG/meetings/44th/44th_MTG_Minute.txt

Add FAPI-SIG 44th meeting minute

---

FAPI-SIG/meetings/45th/45th_MTG_Minute.txt

Add FAPI-SIG 45th meeting minute

---

README.md

Rename FAPI-SIG to OAuth SIG

---

OAuth-SIG/meetings/1st/1st_MTG_Minute.txt

Add OAuth SIG 1st meeting minute

---

keycloak/Dockerfile

Proposal to fix this issue: https://github.com/keycloak/kc-sig-fapi/issues/382
Based on this documentation: https://www.keycloak.org/server/containers#_installing_additional_rpm_packages

Updated dockerfile to install curl and enable the healthcheck feature

---

.env
README.md

Update Keycloak images to 21.1.2

---

OAuth-SIG/meetings/2nd/2nd_MTG_Minute.txt

Add OAuth SIG 2nd meeting minute

---

README.md

revise the section of Passed Conformance Tests per Keycloak version

---

OAuth-SIG/meetings/3rd/presentations/3rd_MTG_Minute.txt

add 3rd meeting minute

---

.env
keycloak/oidf.json

fix .env file

---

OAuth-SIG/meetings/4th/4th_MTG_Minute.txt

add 4th meeting minute

---

.env
README.md

Update Keycloak images to 22.0.5

---

OAuth-SIG/meetings/5th/5th_MTG_Minute.txt

Add 5th meeting minute

---

README.md

Update Result section

---

README.md

Update Keycloak images to 23.0.0

---

OAuth-SIG/Breakouts/OID4VCs/2nd/2nd_breakout_session_minute.txt

Add OID4VCI 2nd breakout session minute

---

OAuth-SIG/meetings/5th/5th_MTG_Minute.txt
OAuth-SIG/meetings/6th/6th_MTG_Minute.txt

Add OAuth SIG 6th meeting minute

---

OAuth-SIG/Breakouts/OID4VCs/3rd/3rd_breakout_session_minute.txt

Add OID4VCI 3rd breakout session minute

---

README.md

Update Standards​ section

---

README.md

Update communication channel section

---

README.md
conformance-tests-env/.env

Update Keycloak images to 23.0.2

---

.github/workflows/run-conformance-tests.yml

Add initial workflow for running conformance tests by github actions

---

README.md

Add other types of contributions

---

conformance-tests-env/.env

Update Keycloak images to 23.0.4

---

README.md
conformance-tests-env/.env
conformance-tests-env/conformance-suite/conformance-suite/Dockerfile

Update Keycloak images to 23.0.5

---

README.md

Update conference section

---

OAuth-SIG/meetings/8th/presentations/8th_MTG_Minute.txt

Add OAuth SIG 8th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 23.0.6

---

README.md
conformance-tests-env/.env
conformance-tests-env/README.md
conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/of-br-fapi1-advanced/of-br-fapi1-advanced-par-private-key-PS256-PS256-automated.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-of-br-fapi1-advanced.json

Support FAPI OP - Brazil Open Finance (FAPI-BR v2)

---

conformance-tests-env/README.md
conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh

TEST_PLAN of OIDC and OIDC for logout - change oidcc to oidc

---

README.md
conformance-tests-env/.env

Update Keycloak images to 23.0.7

---

README.md
conformance-tests-env/.env

Update Keycloak images to 24.0.0

---

README.md
conformance-tests-env/.env

Update Keycloak images to 24.0.1

---

OAuth-SIG/meetings/9th/9th_MTG_Minute.txt

Add 9th meeting minute

---

README.md

Update latest achievement by the end of FY2024

---

README.md
conformance-tests-env/.env

Update Keycloak images to 24.0.2

---

README.md

Update latest achievement by April 2024

---

OAuth-SIG/meetings/10th/10th_MTG_Minute.txt

Add 10th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 24.0.3

---

README.md
conformance-tests-env/.env

Update Keycloak images to 24.0.4

---

README.md
members.adoc

Update a front page

---

README.md

Follow-up Issue 566

---

README.md
conformance-tests-env/.env

Update Keycloak images to 24.0.5

---

README.md
conformance-tests-env/.env
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi-aus-cdr.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi-ciba.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi-uk-ob.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi1-advanced.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi2-ms-id2.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi2-sp-id2.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-ob-br-fapi1-advanced.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-of-br-fapi1-advanced.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-oidc-logout.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-oidc.json

Update Keycloak images to 25.0.0

---

README.md
conformance-tests-env/.env

Update Keycloak images to 25.0.1

---

conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi-ciba.json

Accelerate execution of fapi-ciba conformance tests

---

OAuth-SIG/meetings/13th/13th_MTG_Minute.txt

Add 13th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 25.0.2

---

OAuth-SIG/meetings/14th/14th_MTG_Minute.txt

add 14th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 25.0.4

---

OAuth-SIG/meetings/15th/15th_MTG_Minute.txt

Add 15th meeting agenda

---

README.md

Add KeyConf 24

---

OAuth-SIG/meetings/16th/16th_MTG_Minute.txt

Add 16th meeting minute

---

README.md
conformance-tests-env/.env
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-basic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-basic-discovery-dynamic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-basic-static-static-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-basic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-basic-discovery-dynamic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-basic-static-static-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-hybrid-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-hybrid-discovery-dynamic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-hybrid-static-static-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-implicit-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-implicit-discovery-dynamic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-formpost-implicit-static-static-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-hybrid-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-hybrid-discovery-dynamic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-hybrid-static-static-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-implicit-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-implicit-discovery-dynamic-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/oidc/oidcc-implicit-static-static-automated.json
conformance-tests-env/docker-compose.yml

Update Keycloak images to 26.0.0

---

OAuth-SIG/meetings/16th/16th_MTG_Minute.txt

Update OAuth SIG 16th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.1

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.2

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.4

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.5

---

conformance-tests-env/spec/entities/dpop-proof-signature-verify-server/main.go

Res server supports RS/PS/ES algorithm

---

conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-OpenID-Connect-DPOP-ES256-ES256.json

Support manual FAPI2 SP ID2 DPoP-MTLS-OIDC conformance test

---

conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-DPOP-private-key-MTLS-PS256-PS256.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi2-sp-id2.json

Support manual FAPI2 SP ID2 DPoP-Private_Key_Jwt-OAuth conformance test

---

conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-DPOP-MTLS-MTLS-ES256-ES256-automated.json

Support automatic FAPI2 SP ID2 DPoP-MTLS-OAuth conformance test

---

conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-ms-id2/fapi2-ID2-FAPI2MS-DPOP-JARM-MTLS-MTLS-ES256-ES256-automated.json
conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi2-ms-id2.json

Support automatic FAPI2 MS ID1 DPoP-MTLS-OAuth-JARM conformance test

---

conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-OpenID-Connect-DPOP-ES256-ES256-automated.json

Support automatic FAPI2 SP ID2 DPoP-MTLS-OIDC conformance test

---

conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-ms-id2/fapi2-ID2-FAPI2MS-DPoP-JAR-MTLS-MTLS-ES256-ES256-automated.json

Support automatic FAPI2 MS ID1 DPoP-MTLS-OAuth-JAR conformance test

---

OAuth-SIG/meetings/17th/17th_MTG_Minute.txt

Add OAuth SIG 17th meeting minute

---

conformance-tests-env/.env

Update Conformance Suite version to 5.1.25

---

conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi1-advanced.json

FAPI 1.0 Advanced: Resolving some warnings about ID Token

---

conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi-uk-ob/fapi-uk-ob-mtls-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi-uk-ob/fapi-uk-ob-mtls-PS256-PS256.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi-uk-ob/fapi-uk-ob-private-key-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-final-with-mtls-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-final-with-mtls-ES256-ES256.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-final-with-mtls-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-final-with-private-key-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-final-with-private-key-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-jarm-mtls-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-jarm-mtls-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-jarm-private-key-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-jarm-private-key-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-jarm-mtls-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-jarm-mtls-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-jarm-mtls-PS256-PS256.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-jarm-private-key-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-jarm-private-key-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-mtls-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-mtls-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-mtls-PS256-PS256.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-private-key-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi1-advanced/fapi1-advanced-par-private-key-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/of-br-fapi1-advanced/of-br-fapi1-advanced-par-private-key-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/of-br-fapi1-advanced/of-br-fapi1-advanced-par-private-key-PS256-PS256.json

UK OpenBanking FAPI1 Advanced: Polishing Test Configuration Files

---

conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi2-sp-id2.json

Add dpop-bind-enforcer to fapi-2-dpop-security-profile

---

conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi2-ms-id1.json

Add dpop-bind-enforcer to fapi-2-dpop-security-profile for FAPI2 MS ID1

---

conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi1-advanced.json

Speed up fapi1-advanced par tests waiting for par expiration

---

conformance-tests-env/test-target/keycloak/keycloak/realms/realm-fapi-aus-cdr.json

Speed up fapi-aus-cdr par tests waiting for par expiration

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.6

---

README.md

Add description about OID4VCI support from Keycloak 25

---

conformance-tests-env/README.md

Add description to run FAPI 2.0 + DPoP conformance tests

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.7

---

OAuth-SIG/meetings/18th/18th_MTG_Minute.pdf

Add OAuth SIG 18th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.0.8

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.1.0

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.1.1

---

README.md

Update Other Contributions

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.1.2

---

OAuth-SIG/meetings/20th/20th_MTG_Minute.txt

Add OAuth SIG 20th meeting minute

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.1.3

---

README.md

Update Other Contributions - OSW 2025

---

README.md

Update Other Contributions - Keycloak DevDay 2025

---

README.md

Update Other Contributions - KeyConf 24

---

README.md

Update Other Contributions - OSS Summit Europe 2025

---

README.md

Update Other Contributions - KeyConf 23

---

README.md

typos - conferences

---

README.md

Update Conferences - KubeCon Europe 2025

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.1.4

---

README.md

Typos in Hosting Conferences

---

README.md

Update Conferences - KubeCon Japan 2025

---

README.md

Update Hosting Conferences

---

conformance-tests-env/.env
conformance-tests-env/conformance-suite/conformance-suite/Dockerfile
conformance-tests-env/conformance-suite/conformance-suite/run-tests.sh
conformance-tests-env/conformance-suite/test-runner/Dockerfile
conformance-tests-env/conformance-suite/test-runner/test-runner-entrypoint.sh
conformance-tests-env/docker-compose.yml
conformance-tests-env/test-target/keycloak/keycloak/keycloak-custom.properties

Update Conformance Suite to 5.1.31

---

conformance-tests-env/README.md

Update Keycloak path in documentation for conformance-tests-env

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.1.5

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.2.0

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.2.1

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.2.2

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.2.3

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.2.4

---

README.md
conformance-tests-env/.env
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-DPOP-MTLS-MTLS-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-DPOP-private-key-MTLS-PS256-PS256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-MTLS-MTLS-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-OpenID-Connect-DPOP-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-OpenID-Connect-ES256-ES256-automated.json
conformance-tests-env/conformance-suite/fapi-conformance-suite-configs/fapi2-sp-id2/fapi2-ID2-FAPI2SP-private-key-MTLS-PS256-PS256-automated.json

Update conformance suite version to 5.1.32

---

README.md

Update Other Contributions - KeyConf 25

---

README.md

Update Other Contributions - Open Source Summit Europe 2025

---

conformance-tests-env/.env

Workaround : bulidx bake bug on windonws

---

conformance-tests-env/.env

Update conformance suite version to 5.1.33

---

README.md

Follow-up ISSUE-820

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.3.1

---

README.md

Follow-up ISSUE-824

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.3.2

---

README.md
conformance-tests-env/.env

Update Keycloak images to 26.3.5

---

README.md

Add Contributions - FAPI 2.0 Final
